
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const meta={dashboard:["Dashboard","Market overview from your DLD transaction database."],upload:["Upload Data","Import DLD CSV or Excel files into PostgreSQL."],analytics:["Market Analytics","Compare transaction activity and pricing across Dubai areas."],valuation:["Property Valuation","Estimate property value using comparable DLD transactions."]};
const money=v=>v==null?"—":Math.abs(+v)>=1e6?`AED ${(v/1e6).toFixed(2)}M`:Math.abs(+v)>=1e3?`AED ${(v/1e3).toFixed(0)}K`:`AED ${(+v).toLocaleString()}`;
const num=v=>v==null?"—":(+v).toLocaleString();
const date=v=>!v?"—":new Date(v).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"});
function safe(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(t){$("#toast").textContent=t;$("#toast").classList.remove("hidden");clearTimeout(window.tt);window.tt=setTimeout(()=>$("#toast").classList.add("hidden"),3000)}
async function api(u,o){const r=await fetch(u,o);const d=await r.json().catch(()=>({detail:"Unexpected server response"}));if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function show(p){$$(".page").forEach(x=>x.classList.toggle("active",x.id===p));$$(".nav[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#title").textContent=meta[p][0];$("#subtitle").textContent=meta[p][1];if(p==="analytics")loadAnalytics();scrollTo({top:0,behavior:"smooth"})}
$$("[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));$$("[data-go]").forEach(b=>b.onclick=()=>show(b.dataset.go));

async function health(){try{await api("/health");$("#apiState").textContent="API healthy";$("#healthBadge").textContent="● API Healthy"}catch{$("#apiState").textContent="API unavailable";$("#healthBadge").textContent="● API Offline"}}
async function summary(){try{const s=await api("/dashboard/summary");$("#mTx").textContent=num(s.total_transactions);$("#mAreas").textContent=num(s.areas_covered);$("#mProjects").textContent=num(s.projects_covered);$("#mPrice").textContent=money(s.average_price);$("#mPpsf").textContent=s.average_ppsf?`AED ${Math.round(s.average_ppsf).toLocaleString()}`:"—";$("#latestTx").textContent=date(s.latest_transaction_date);$("#lastIngest").textContent=date(s.last_ingestion_date)}catch(e){toast(e.message)}}

async function loadAnalytics(){try{const d=await api(`/analytics/areas?lookback_days=${$("#days").value||365}`);const a=d.areas||[];renderAnalytics(a);renderBars(a.slice(0,7))}catch(e){toast(e.message)}}
$("#refresh").onclick=loadAnalytics;
function renderAnalytics(a){const total=a.reduce((s,x)=>s+(x.transactions||0),0), w=f=>total?a.reduce((s,x)=>s+(+x[f]||0)*(x.transactions||0),0)/total:null;$("#aTx").textContent=num(total);$("#aAreas").textContent=num(a.length);$("#aPrice").textContent=money(w("average_price"));$("#aPpsf").textContent=w("average_ppsf")?`AED ${Math.round(w("average_ppsf")).toLocaleString()}`:"—";$("#analyticsBody").innerHTML=a.map(x=>`<tr><td><b>${safe(x.area)}</b></td><td>${num(x.transactions)}</td><td>${money(x.average_price)}</td><td>${money(x.median_price)}</td><td>AED ${Math.round(x.average_ppsf||0).toLocaleString()}</td><td>AED ${Math.round(x.median_ppsf||0).toLocaleString()}</td><td>${money(x.min_price)}</td><td>${money(x.max_price)}</td></tr>`).join("")}
function renderBars(a){const m=Math.max(...a.map(x=>x.transactions||0),1);$("#bars").innerHTML=a.map(x=>`<div class="bar"><b title="${safe(x.area)}">${safe(x.area)}</b><div class="track"><i style="width:${((x.transactions||0)/m*100).toFixed(1)}%"></i></div><em>${num(x.transactions)}</em></div>`).join("")}

const drop=$("#drop"),file=$("#file");drop.ondragover=e=>{e.preventDefault();drop.classList.add("drag")};drop.ondragleave=()=>drop.classList.remove("drag");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("drag");if(e.dataTransfer.files[0])pick(e.dataTransfer.files[0])};file.onchange=()=>file.files[0]&&pick(file.files[0]);
function pick(f){window.dld=f;$("#fileInfo").classList.remove("hidden");$("#fileInfo").textContent=`${f.name} · ${(f.size/1024/1024).toFixed(2)} MB`;$("#ingest").disabled=false}
$("#ingest").onclick=async()=>{if(!window.dld)return;$("#ingest").disabled=true;$("#ingest").textContent="Processing...";const fd=new FormData();fd.append("file",window.dld);try{const r=await api("/ingest/dld",{method:"POST",body:fd});$("#ingestResult").classList.remove("hidden");$("#ingestResult").innerHTML=`<b>Data ingestion completed</b><div class="notice-grid"><div><span>Raw rows</span><b>${num(r.raw_rows)}</b></div><div><span>Valid rows</span><b>${num(r.valid_rows)}</b></div><div><span>Inserted</span><b>${num(r.inserted)}</b></div><div><span>Duplicates</span><b>${num(r.duplicates_skipped)}</b></div></div>`;toast("DLD data ingested successfully");await summary();await loadAnalytics()}catch(e){$("#ingestResult").classList.remove("hidden");$("#ingestResult").textContent=`Ingestion failed: ${e.message}`}finally{$("#ingest").disabled=false;$("#ingest").textContent="Ingest Data"}}

async function options(){try{const m=await api("/meta/options");$("#vArea").innerHTML=(m.areas||[]).map(x=>`<option>${safe(x)}</option>`).join("");$("#projects").innerHTML=(m.projects||[]).map(x=>`<option value="${safe(x)}"></option>`).join("");$("#vSubtype").innerHTML=(m.property_subtypes||[]).map(x=>`<option>${safe(x)}</option>`).join("");$("#vBeds").innerHTML=(m.bedrooms||[]).map(x=>`<option value="${x}">${x}</option>`).join("");if((m.areas||[]).includes("JUMEIRAH VILLAGE CIRCLE"))$("#vArea").value="JUMEIRAH VILLAGE CIRCLE";if((m.property_subtypes||[]).includes("Villa"))$("#vSubtype").value="Villa";if((m.bedrooms||[]).includes(3))$("#vBeds").value="3"}catch(e){toast(e.message)}}
$("#valuationForm").onsubmit=async e=>{e.preventDefault();const p={area:$("#vArea").value,project:$("#vProject").value.trim()||null,property_subtype:$("#vSubtype").value||null,bedrooms:$("#vBeds").value?+$("#vBeds").value:null,size_sqm:+$("#vSize").value,asking_price:$("#vAsk").value?+$("#vAsk").value:null,lookback_days:+$("#vDays").value,max_size_difference:+$("#vDiff").value,max_comparables:10};try{renderVal(await api("/valuation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}))}catch(e){toast(e.message)}};
function renderVal(r){$("#emptyVal").classList.add("hidden");$("#valResult").classList.remove("hidden");$("#compPanel").classList.remove("hidden");$("#rValue").textContent=money(r.estimated_market_value);$("#rRange").textContent=`Range ${money(r.estimated_low)} – ${money(r.estimated_high)}`;$("#rPpsf").textContent=`AED ${Math.round(r.estimated_ppsf).toLocaleString()}`;const d=r.asking_vs_estimate_pct;$("#rAsk").textContent=d==null?"—":`${d>0?"+":""}${(+d).toFixed(1)}%`;$("#rComps").textContent=num(r.comparables_count);$("#rEligible").textContent=num(r.eligible_transactions);$("#rConf").textContent=`${Math.round(r.confidence_score)}/100`;$("#confBar").style.width=`${Math.max(0,Math.min(100,r.confidence_score))}%`;let t=`Confidence is ${r.confidence_score>=75?"high":r.confidence_score>=55?"moderate":"low"}. `;if(d!=null)t+=d>8?`The asking price is ${Math.abs(d).toFixed(1)}% below the central estimate. Treat this as a potential opportunity, not a definitive below-market conclusion.`:d<-8?`The asking price is ${Math.abs(d).toFixed(1)}% above the central estimate.`:`The asking price is close to the central estimate.`;$("#insight").textContent=t;$("#method").textContent=r.methodology;$("#compsBody").innerHTML=(r.comparables||[]).map(c=>`<tr><td>${date(c.date)}</td><td><b>${safe(c.project||"—")}</b></td><td>${c.bedrooms??"—"}</td><td>${(+c.size_sqm).toFixed(1)}</td><td>${money(c.transaction_value)}</td><td>AED ${Math.round(c.price_per_sqft).toLocaleString()}</td><td>${(+c.size_difference_pct).toFixed(1)}%</td><td>${c.recency_days}d</td><td>${(+c.similarity_score).toFixed(1)}</td></tr>`).join("")}
(async()=>{await health();await Promise.all([summary(),loadAnalytics(),options()])})()
